
import React from 'react';
import {
    Bot, BrainCircuit, CheckCircle, Plus, Sparkles, Upload, Megaphone, User,
    ShieldQuestion, Search, MessageCircle, PenTool, Clock2, Wallet, BadgeCheck,
    ClipboardList, Target, LineChart, Users2, Network, LayoutTemplate, Video,
    Instagram, FileText, Globe, FileSearch, KeyRound, BarChart3, Newspaper,
    Handshake, Filter, ListChecks, Container, BotMessageSquare, Terminal,
    FileCheck, Palette, Map, LandPlot, Building2, Camera, Calculator, Album, Wand2, Database
} from 'lucide-react';
import type { Feature } from '@/lib/tools-client';

export const tools: Omit<Feature, 'details' | 'longDescription' | 'creationFields' | 'renderResult'>[] = [
    // === Meta Pilot (Campaign Automation) ===
    {
        id: 'meta-auto-pilot',
        title: "Meta Auto Pilot",
        description: "The single-click manager for your entire Meta suite.",
        icon: <Terminal />,
        color: '#0078FF',
        categories: ['Ads', 'Marketing'],
        badge: 'AUTO',
        cta: "Launch Pilot",
        mindMapCategory: "Meta Pilot (Campaign Automation)",
        isPage: false,
        href: "/dashboard/tool/meta-auto-pilot",
        guideHref: "/apps/meta-auto-pilot",
    },
    {
        id: 'campaign-builder',
        title: "Campaign Builder",
        description: "Your dedicated agent for Facebook & Instagram advertising.",
        icon: <BotMessageSquare />,
        color: '#00A4FF',
        categories: ['Ads', 'Marketing', 'Lead Gen'],
        cta: "Build a Campaign",
        mindMapCategory: "Meta Pilot (Campaign Automation)",
        isPage: false,
        href: "/dashboard/tool/campaign-builder",
        guideHref: "/apps/campaign-builder",
    },
    {
        id: 'audience-creator',
        title: "Audience Creator",
        description: "Find high-intent buyers before they search.",
        icon: <Users2 />,
        color: '#00C2FF',
        categories: ['Ads', 'Lead Gen', 'Market Intelligence'],
        cta: "Find Your Audience",
        mindMapCategory: "Meta Pilot (Campaign Automation)",
        isPage: false,
        href: "/dashboard/tool/audience-creator",
        guideHref: "/apps/audience-creator",
    },
    {
        id: 'insta-ads-designer',
        title: "Insta Ads Designer",
        description: "Create perfect ads for Instagram Stories & Feed.",
        icon: <Instagram />,
        color: '#D43F9D',
        categories: ['Ads', 'Creative', 'Social & Comms'],
        cta: "Design an Ad",
        mindMapCategory: "Meta Pilot (Campaign Automation)",
        isPage: false,
        href: "/dashboard/tool/insta-ads-designer",
        guideHref: "/apps/insta-ads-designer",
    },
    // === Archy (Creative Marketing) ===
    {
        id: 'reel-ads',
        title: "Reel Ads",
        description: "Generate engaging video ads for Instagram Reels.",
        icon: <Video />,
        color: '#C13584',
        categories: ['Ads', 'Creative', 'Social & Comms'],
        badge: 'NEW',
        cta: "Create a Reel",
        mindMapCategory: "Archy (Creative Marketing)",
        isPage: false,
        href: "/dashboard/tool/reel-ads",
        guideHref: "/apps/reel-ads",
    },
    {
        id: 'instagram-admin',
        title: "Instagram Admin",
        description: "Schedules posts and handles replies on Instagram.",
        icon: <Bot />,
        color: '#833AB4',
        categories: ['Social & Comms', 'Marketing'],
        badge: 'AUTO',
        cta: "Manage Instagram",
        mindMapCategory: "Archy (Creative Marketing)",
        isPage: false,
        href: "/dashboard/tool/instagram-admin",
        guideHref: "/apps/instagram-admin",
    },
    {
        id: 'story-planner',
        title: "Story Planner",
        description: "Plan and design animated Instagram stories.",
        icon: <Album />,
        color: '#F56040',
        categories: ['Creative', 'Social & Comms'],
        cta: "Plan a Story",
        mindMapCategory: "Archy (Creative Marketing)",
        isPage: false,
        href: "/dashboard/tool/story-planner",
        guideHref: "/apps/story-planner",
    },
    {
        id: 'ai-video-presenter',
        title: "AI Video Presenter",
        description: "Create a lifelike AI presenter to deliver your project pitch.",
        icon: <Video />,
        color: '#4A90E2',
        categories: ['Creative', 'Marketing', 'Ads'],
        cta: "Create Your Presenter",
        mindMapCategory: "Archy (Creative Marketing)",
        isPage: false,
        href: "/dashboard/tool/ai-video-presenter",
        guideHref: "/apps/ai-video-presenter",
    },
    {
        id: 'ugc-script-writer',
        title: "UGC Script Writer",
        description: "Generate authentic, user-generated content style video ad scripts.",
        icon: <MessageCircle />,
        color: '#B8E986',
        categories: ['Creative', 'Social & Comms', 'Ads'],
        cta: "Write Your Script",
        mindMapCategory: "Archy (Creative Marketing)",
        isPage: false,
        href: "/dashboard/tool/ugc-script-writer",
        guideHref: "/apps/ugc-script-writer",
    },
    {
        id: 'youtube-video-editor',
        title: "AI YouTube Video Editor",
        description: "Edit any video to be YouTube-ready.",
        icon: <Video />,
        color: '#FF0000',
        categories: ['Editing', 'Creative'],
        badge: 'NEW',
        cta: "Edit a Video",
        mindMapCategory: "Archy (Creative Marketing)",
        isPage: true,
        href: "/dashboard/tool/youtube-video-editor",
        guideHref: "/apps/youtube-video-editor",
    },
    {
        id: 'landing-pages',
        title: "Landing Page Builder",
        description: "Launch a high-converting page in minutes.",
        icon: <LayoutTemplate />,
        color: '#9013FE',
        categories: ['Web', 'Marketing', 'Lead Gen'],
        cta: "Build Your Page",
        mindMapCategory: "Archy (Creative Marketing)",
        isPage: false,
        href: "/dashboard/tool/landing-pages",
        guideHref: "/apps/landing-page-builder",
    },
    {
        id: 'rebranding',
        title: "Automated Rebranding",
        description: "Apply your brand identity to any brochure with text-based commands.",
        icon: <Palette />,
        color: '#F5A623',
        categories: ['Creative', 'Editing', 'Sales Tools'],
        cta: "Rebrand a Document",
        mindMapCategory: "Archy (Creative Marketing)",
        isPage: false,
        href: "/dashboard/tool/rebranding",
        guideHref: "/apps/automated-rebranding",
    },
    {
        id: 'brochure-translator',
        title: "Brochure Translator",
        description: "Translate any brochure to multiple languages in seconds.",
        icon: <Globe />,
        color: '#7ED321',
        categories: ['Editing', 'Sales Tools'],
        cta: "Translate a Brochure",
        mindMapCategory: "Archy (Creative Marketing)",
        isPage: false,
        href: "/dashboard/tool/brochure-translator",
        guideHref: "/apps/brochure-translator",
    },
    {
        id: 'pdf-editor',
        title: "Visual PDF Editor (Deprecated)",
        description: "A legacy tool for simple PDF edits.",
        icon: <FileText />,
        color: '#888888',
        categories: ['Editing'],
        badge: 'DEPRECATED',
        cta: "Open Editor",
        mindMapCategory: "Archy (Creative Marketing)",
        isPage: true,
        href: "/dashboard/tool/pdf-editor",
        guideHref: "/apps/visual-pdf-editor",
    },
    {
        id: 'aerial-view-generator',
        title: "Aerial View Generator",
        description: "Create cinematic, aerial video tours of any property.",
        icon: <Camera />,
        color: '#50E3C2',
        categories: ['Creative', 'Marketing', 'Ads'],
        badge: 'NEW',
        cta: "Generate Aerial Tour",
        mindMapCategory: "Archy (Creative Marketing)",
        isPage: false,
        href: "/dashboard/tool/aerial-view-generator",
        guideHref: "/apps/aerial-view-generator",
    },
    // === Listing & CRM Tools ===
    {
        id: 'listing-manager',
        title: "Listing Manager",
        description: "Your central hub to prepare and syndicate listings to major portals.",
        icon: <ListChecks />,
        color: '#FF6F61',
        categories: ['CRM', 'Sales Tools'],
        cta: "Manage Listings",
        mindMapCategory: "Listing & CRM Tools",
        isPage: true,
        href: "/dashboard/tool/listing-manager",
        guideHref: "/apps/listing-manager",
    },
    {
        id: 'listing-performance',
        title: "Listing Performance",
        description: "Track listing views and performance.",
        icon: <BarChart3 />,
        color: '#FF8C42',
        categories: ['CRM', 'Market Intelligence'],
        cta: "View Performance",
        mindMapCategory: "Listing & CRM Tools",
        isPage: true,
        href: "/dashboard/tool/listing-performance",
        guideHref: "/apps/listing-performance",
    },
    {
        id: 'listing-generator',
        title: "Listing Generator",
        description: "Craft perfect listings for portals like Property Finder & Bayut.",
        icon: <PenTool />,
        color: '#FFC107',
        categories: ['Sales Tools', 'Marketing', 'Web'],
        cta: "Write Your Listing",
        mindMapCategory: "Listing & CRM Tools",
        isPage: false,
        href: "/dashboard/tool/listing-generator",
        guideHref: "/apps/listing-generator",
    },
    {
        id: 'propertyfinder-sync',
        title: "Property Finder Pilot",
        description: "The execution terminal for pushing listings to Property Finder.",
        icon: <Container />,
        color: '#6610F2',
        categories: ['Developer', 'CRM'],
        badge: 'AUTO',
        cta: "Initiate Sync",
        mindMapCategory: "Listing & CRM Tools",
        isPage: true,
        href: "/dashboard/tool/property-finder-sync",
        guideHref: "/apps/property-finder-pilot",
    },
    {
        id: 'bayut-sync',
        title: "Bayut Pilot",
        description: "The execution terminal for pushing listings to Bayut.",
        icon: <Container />,
        color: '#28A745',
        categories: ['Developer', 'CRM'],
        badge: 'AUTO',
        cta: "Initiate Sync",
        mindMapCategory: "Listing & CRM Tools",
        isPage: true,
        href: "/dashboard/tool/bayut-sync",
        guideHref: "/apps/bayut-pilot",
    },
    {
        id: 'ai-price-estimator',
        title: "AI Price Estimator",
        description: "Get an AI-powered price estimate for any property.",
        icon: <Calculator />,
        color: '#6F42C1',
        categories: ['Market Intelligence', 'Sales Tools'],
        cta: "Estimate a Price",
        mindMapCategory: "Listing & CRM Tools",
        isPage: false,
        href: "/dashboard/tool/ai-price-estimator",
        guideHref: "/apps/ai-price-estimator",
    },
    {
        id: 'commission-calculator',
        title: "Commission Calculator",
        description: "Instantly calculate your sales commission.",
        icon: <Wallet />,
        color: '#20C997',
        categories: ['Sales Tools'],
        cta: "Calculate Commission",
        mindMapCategory: "Listing & CRM Tools",
        isPage: false,
        href: "/dashboard/tool/commission-calculator",
        guideHref: "/apps/commission-calculator",
    },
    {
        id: 'payment-planner',
        title: "Payment Planner",
        description: "Generate tailored payment plans for off-plan properties.",
        icon: <ClipboardList />,
        color: '#FD7E14',
        categories: ['Sales Tools'],
        cta: "Create a Plan",
        mindMapCategory: "Listing & CRM Tools",
        isPage: false,
        href: "/dashboard/tool/payment-planner",
        guideHref: "/apps/payment-planner",
    },
    {
        id: 'investor-matching',
        title: "Investor Matching",
        description: "Pair budgets with the right projects.",
        icon: <Handshake />,
        color: '#17A2B8',
        categories: ['Lead Gen', 'Sales Tools', 'CRM'],
        cta: "Match Investors",
        mindMapCategory: "Listing & CRM Tools",
        isPage: false,
        href: "/dashboard/tool/investor-matching",
        guideHref: "/apps/investor-matching",
    },
    {
        id: 'multi-offer-builder',
        title: "Multi-Offer Builder",
        description: "Compare property options side-by-side for clients.",
        icon: <LayoutTemplate />,
        color: '#E83E8C',
        categories: ['Sales Tools'],
        cta: "Build an Offer",
        mindMapCategory: "Listing & CRM Tools",
        isPage: false,
        href: "/dashboard/tool/multi-offer-builder",
        guideHref: "/apps/multi-offer-builder",
    },
    {
        id: 'whatsapp-campaigns',
        title: "WhatsApp Manager",
        description: "Send personalized broadcasts and drip campaigns.",
        icon: <MessageCircle />,
        color: '#25D366',
        categories: ['Social & Comms', 'CRM', 'Marketing'],
        cta: "Manage WhatsApp",
        mindMapCategory: "Listing & CRM Tools",
        isPage: false,
        href: "/dashboard/tool/whatsapp-manager",
        guideHref: "/apps/whatsapp-manager",
    },
    {
        id: 'lead-investigator',
        title: "Lead Investigator AI",
        description: "Find social profiles and professional history for any lead.",
        icon: <FileSearch />,
        color: '#DC3545',
        categories: ['Lead Gen', 'Sales Tools', 'CRM'],
        cta: "Investigate a Lead",
        mindMapCategory: "Listing & CRM Tools",
        isPage: false,
        href: "/dashboard/tool/lead-investigator",
        guideHref: "/apps/lead-investigator-ai",
    },
    // === Market Intelligence ===
    {
        id: 'projects-finder',
        title: "Market Library",
        description: "Search our intelligent library for verified projects.",
        icon: <Search />,
        color: '#6C757D',
        categories: ['Market Intelligence', 'Market Library'],
        cta: "Search the Library",
        mindMapCategory: "Market Intelligence",
        isPage: true,
        href: "/dashboard/tool/projects-finder",
        guideHref: "/apps/market-library",
    },
    {
        id: 'market-reports',
        title: "Market Reports",
        description: "Generate PDF reports on market trends, pricing, and sentiment.",
        icon: <Newspaper />,
        color: '#28A745',
        categories: ['Market Intelligence', 'Sales Tools'],
        cta: "Generate a Report",
        mindMapCategory: "Market Intelligence",
        isPage: false,
        href: "/dashboard/tool/market-reports",
        guideHref: "/apps/market-reports",
    },
    {
        id: 'market-trends',
        title: "Market Trends Watcher",
        description: "Identify emerging market trends before they become mainstream.",
        icon: <LineChart />,
        color: '#17A2B8',
        categories: ['Market Intelligence'],
        cta: "Watch Trends",
        mindMapCategory: "Market Intelligence",
        isPage: true,
        href: "/dashboard/tool/market-trends",
        guideHref: "/apps/market-trends-watcher",
    },
     {
        id: 'deal-analyzer',
        title: "Deal Analyzer",
        description: "Analyze the investment potential of any real estate deal, from cap rate to cash flow.",
        icon: <BarChart />,
        color: '#007BFF',
        categories: ['Market Intelligence', 'Sales Tools'],
        badge: 'NEW',
        cta: "Analyze a Deal",
        mindMapCategory: 'Market Intelligence',
        isPage: false,
        href: "/dashboard/tool/deal-analyzer",
        guideHref: "/apps/deal-analyzer",
    },
     {
        id: 'keyword-planner',
        title: 'Keyword Planner',
        description: 'Generate strategic keyword plans for Google Ads to capture high-intent leads.',
        icon: <KeyRound />,
        color: '#ff6b6b',
        categories: ['Ads', 'Market Intelligence'],
        cta: 'Plan Keywords',
        mindMapCategory: 'Meta Pilot (Campaign Automation)',
        isPage: true,
        href: '/dashboard/tool/keyword-planner',
        guideHref: '/apps/keyword-planner',
    },

    // === Core Platform ===
    {
        id: 'ai-brand-creator',
        title: "Brand Creator",
        description: "Configure your entire brand kit by analyzing uploaded documents.",
        icon: <Palette />,
        color: '#6F42C1',
        categories: ['CRM', 'Developer'],
        cta: "Configure Your Brand",
        mindMapCategory: "Core Platform",
        isPage: false,
        href: "/dashboard/tool/brand-creator",
        guideHref: "/apps/brand-creator",
    },
    {
        id: 'crm-assistant',
        title: "CRM Memory",
        description: "The core data store that remembers every client interaction.",
        icon: <Database />,
        color: '#343A40',
        categories: ['CRM', 'Developer'],
        cta: "View Memory",
        mindMapCategory: "Core Platform",
        isPage: false,
        href: "/dashboard/tool/crm-assistant",
        guideHref: "/apps/crm-memory",
    },
    {
        id: 'ai-assistant',
        title: "Assistant",
        description: "Your personal, trainable AI partner.",
        icon: <Bot />,
        color: '#007BFF',
        categories: ['CRM', 'Sales Tools'],
        cta: "Open Assistant",
        mindMapCategory: "Core Platform",
        isPage: false,
        href: "/dashboard/tool/assistant",
        guideHref: "/apps/assistant",
    },
    {
        id: 'chatbot-creator',
        title: "Embeddable Site Assistant",
        description: "Add a market-aware AI chatbot to any website.",
        icon: <BotMessageSquare />,
        color: '#0056b3',
        categories: ['Web', 'Lead Gen'],
        badge: 'NEW',
        cta: "Get Embed Code",
        mindMapCategory: "Core Platform",
        isPage: true,
        href: "/dashboard/tool/chatbot-creator",
        guideHref: "/apps/embeddable-site-assistant",
    },
    {
        id: 'vm-creator',
        title: "VM Creator",
        description: "A utility for developers to provision Google Cloud virtual machines.",
        icon: <Terminal />,
        color: '#ADB5BD',
        categories: ['Developer'],
        badge: 'AUTO',
        cta: "Provision VM",
        mindMapCategory: "Core Platform",
        isPage: false,
        href: "/dashboard/tool/vm-creator",
        guideHref: "/apps/vm-creator",
    },
    {
        id: 'creative-execution-terminal',
        title: "Creative Execution Terminal",
        description: "The execution engine for complex creative tasks.",
        icon: <Wand2 />,
        color: '#495057',
        categories: ['Creative', 'Developer'],
        cta: "Open Terminal",
        mindMapCategory: "Core Platform",
        isPage: false,
        href: "/dashboard/tool/creative-execution-terminal",
        guideHref: "/apps/creative-execution-terminal",
    },
];
